export const weddingText = {
    "fr": {
        "intro" : "Le plus beau jour de votre vie à Marrakech",
        "grand titre" : "Les petites, comme les grandes familles sont les bienvenues !",
        "text intro" : "Votre mariage est pour bientôt ? Félicitations les amoureux ! Un moment aussi beau que l’union de deux personnes doit être célébré d’une manière originale. Et si vous fêtez votre mariage à Marrakech ? Rassurez-vous, ce n’est pas compliqué et cela ne vous coûtera pas une fortune. De nombreux couples ont fait confiance à notre wedding planner à Marrakech.",
        "text" : "Un mariage à Marrakech est un choix incontestablement avantageux ! D’une part vous fêtez cet évènement dans un cadre plus que fascinant, d’autre part vous choisissez une belle destination pour votre lune de miel. Monuments historiques, richesse culturelle, sites naturels fascinants et cerise sur gâteau : un climat méditerranéen fort agréable. Nul souci pour le logement des mariés et de leurs invités. Nous vous proposons plusieurs demeures qui rivalisent en matière de beauté de style et de performance des équipements. La Villa Adnaa ou encore la Villa Mexance sont situées dans des emplacements stratégiques : des zones calmes mais proches du centre-ville et des points d’intérêt.",
        "question" : "Pourquoi recourir aux services d’un wedding planner à Marrakech?",
        "reponse" : "Certes, le mariage est un évènement heureux mais ses préparatifs sont souvent épuisants et même stressants. Avec un emploi de temps chargé les choses peuvent devenir compliquées ! Préservez votre énergie et confiez la tâche à un wedding planner professionnel. Avec 15 ans d’expérience et une équipe de collaborateurs passionnés et compétents, nous sommes la bonne adresse pour l’organisation d’un mariage à Marrakech. Comptez sur nous pour s’occuper du tout : fête, animation, hébergement, repas, etc. Nos photographes sont là pour éterniser ces beaux moments avec une belle touche artistique.\nN’hésitez pas à nous contacter et nous parler de vos rêves et caprices pour cette journée exceptionnelle. Nous sommes capables d’envisager des solutions sur mesure pour rendre votre fête de Mariage au Maroc encore plus heureuse et mémorable."
    },
    "an": {
        "intro" : "The best day of your life in Marrakech",
        "grand titre" : "Both small and large families are welcome!",
        "text intro" : "Your wedding is coming soon? Congratulations lovers! A moment as beautiful as the union of two people must be celebrated in an original way. And if you celebrate your wedding in Marrakech? Don't worry, it's not complicated and it won't cost you a fortune. Many couples have trusted our wedding planner in Marrakech.",
        "text" : "A wedding in Marrakech is an undeniably advantageous choice! On the one hand you celebrate this event in a more than fascinating setting, on the other hand you choose a beautiful destination for your honeymoon. Historical monuments, cultural richness, fascinating natural sites and icing on the cake: a very pleasant Mediterranean climate. No worries about the accommodation of the bride and groom and their guests. We offer several residences that compete in terms of beauty of style and performance of equipment. Villa Adnaa or Villa Mexance are located in strategic locations: quiet areas but close to the city center and points of interest.",
        "question" : "Why use the services of a wedding planner in Marrakech",
        "repoonse" : "Admittedly, marriage is a happy event, but its preparations are often exhausting and even stressful. With a busy schedule things can get complicated! Save your energy and entrust the task to a professional wedding planner. With 15 years of experience and a team of passionate and competent collaborators, we are the right address for the organization of a wedding in Marrakech. Count on us to take care of everything: party, entertainment, accommodation, meals, etc. Our photographers are there to perpetuate these beautiful moments with a beautiful artistic touch.\nDo not hesitate to contact us and tell us about your dreams and whims for this exceptional day. We are able to consider tailor-made solutions to make your wedding party in Morocco even more happy and memorable."
    }
}