export const seminaryText = {
    "fr": {
        "intro" : "Confiez votre séminaire à des spécialistes avec Séminaire Marrakech",
        "grand titre" : "Les petites, comme les grandes familles sont les bienvenues !",
        "text" : "Un Séminaire Marrakech pour une entreprise est aujourd’hui important pour maintenir une bonne cohésion et une bonne entente au sein de votre entreprise.\n\nEn effet, les séjours d’entreprise sont de plus en plus nombreux et se développent davantage vers les pays étrangers. Aujourd’hui, Marrakech est la destination « star » pour organiser vos séminaires. Car la ville rouge vous offre de nombreuses activités à réaliser pour votre équipe au cœur d’un paysage magnifique.\n\nAlors pendant votre séjour, entre deux réunions, profitez des monuments uniques de Marrakech, de ses merveilleux jardins et des activités sportives ou excursions qui vous sont proposées. De plus, Find Your Concierge met à votre disposition une équipe pour l’organisation de votre séminaire d’entreprise, afin de répondre à tous vos besoins.\n\nFind Your Concierge est le professionnel pour la location de villas de luxe à Marrakech. Profiter d’une de nos nombreuses villas pour votre séjour, que vous soyez 10, 200 personnes ou 400 personnes. Find Your Concierge est à votre écoute pour réaliser votre séminaire et pour que vous en gardiez un souvenir hors du commun !\n\nDécouvrez tous les riads et villas pour votre Séminaires Marrakech.\n\nSéjour pro Marrakech : L’expérience, ça compte.\nDepuis 2002, Find Your Concierge organise régulièrement des ­manifestations pour les groupes, nous répondons à votre demande et faisons de votre projet un souvenir inoubliable.\n\nDans nos clubs house et tentes Caïdales typiques, nous organisons la ­soirée de gala ou d’anniversaire de votre société.\n\n5 villas et palaces  sont à votre disposition pour des réceptions de grands standings :\nLa Villa DemDem et Lions Palace : Jusqu’à 400 personnes\nVilla ADNAA : Jusqu’à 200 personnes\nPalais Tika et Dar Moira : respectivement 100 et 60 personnes le jour de l’évènement.\n\nSéjour entreprise Marrakech\n\nTout est possible pour recevoir et motiver une équipe ou un client. En effet, une villa à Marrakech est l’endroit rêvé pour ces événements, elle vous ouvre les bras et ­propose un choix inépuisable d’activités culturelles ou sportives riches et ­variées. Alors dormez tranquille, on s’occupe de tout, Find Your Concierge saura recevoir vos lauréats.\n• Remercier un collaborateur méritant\n• Fêter une certification ISO\n• Fidéliser un client\n• Stimuler les ventes d’un produit\n• Challenger vos commerciaux\n• Inviter vos meilleurs clients",
        "partenaire" : "Ils nous font confiance depuis de nombreuses années :"
    },
    "an": {
        "intro" : "Entrust your seminar to specialists with Séminaire Marrakech",
        "grand titre" : "Both small and large families are welcome!",
        "text" : "A Marrakech Seminar for a company is important today to maintain good cohesion and a good understanding within your company.\n\nIndeed, company stays are more and more numerous and are developing more towards the countries strangers. Today, Marrakech is the 'star' destination for organizing your seminars. Because the red city offers you many activities to carry out for your team in the heart of a magnificent landscape.\n\nSo during your stay, between two meetings, take advantage of the unique monuments of Marrakech, its wonderful gardens and sports or excursions that are offered to you. In addition, Find Your Concierge provides you with a team for the organization of your business seminar, in order to meet all your needs.\n\nFind Your Concierge is the professional for the rental of luxury villas in Marrakech. Take advantage of one of our many villas for your stay, whether you are 10, 200 people or 400 people. Find Your Concierge is at your disposal to carry out your seminar and so that you keep an extraordinary memory of it!\n\nDiscover all the riads and villas for your Seminars in Marrakech.\n\nPro stay in Marrakech: Experience matters .\nSince 2002, Find Your Concierge regularly organizes events for groups, we respond to your request and make your project an unforgettable memory.\n\nIn our clubhouses and typical Caidal tents, we organize the gala or diner evening. anniversary of your company.\n\n5 villas and palaces are available for high-end receptions:\nVilla DemDem and Lions Palace: Up to 400 people\nVilla ADNAA: Up to 200 people\nTika Palace and Dar Moira: respectively 100 and 60 people on the day of the event.\n\nBusiness stay Marrakech\n\nEverything is possible to receive and motivate a team or a client. Indeed, a villa in Marrakech is the perfect place for these events, it opens its arms to you and offers an inexhaustible choice of rich and varied cultural or sporting activities. So rest easy, we'll take care of everything, Find Your Concierge will know how to receive your laureates.\n• Thank a deserving employee\n• Celebrate ISO certification\n• Build customer loyalty\n• Stimulate product sales\ n• Challenge your salespeople\n• Invite your best customers",
        "partenaire" : "They have trusted us for many years:"
    }
}