export const birthdayText = {
    "fr": {
        "intro" : "Venez faire la fête à Marrakech !",
        "grand titre" : "20 ans, 50 ans, etc.\n10 ans de mariage, 50 ans de mariage, etc.",
        "text" : "Depuis 2017, findyourconcierge.com a réalisé des dizaines de fêtes d’anniversaire.\nAlors quelle que soit la circonstance, nous ferons de ce jour magique un jour inoubliable.\nDonc faîtes-nous part de votre rêve et nous le réalisons ! Des fêtes simples aux plus sophistiquées nous avons des expériences.\n\nRéalisez des fêtes très économiques et envisager de prévoir votre fête plutôt en semaine que le week-end.\nEn effet, les week-ends sont souvent très chargés pour nous et nous sommes très souples sur nos tarifs si votre fête a lieu plutôt en semaine. Alors faîtes nous part de votre projet et vous serez surpris de la rapidité et la précision avec laquelle nous vous répondons.\n\nTout est possible et envisageable grâce à nos nombreuses années d’expérience dans l’organisation d’évènement à Marrakech :\n\nCracheur de feu\nMusiciens locaux – Groupe de Gnaouas\nDJ expérimenté et professionnel\nSon BOSE – RVS\nLight Show et mise en valeur des végétaux et du manoir\nDanseuses orientales\nPrésence de chameaux \nLancé de lanternes Thaï\nMais au risque de nous répéter : c’est surtout notre expérience de la fête qui sera le succès de votre séjour anniversaire, parce que nous prévoyons tout et nous ne laissons rien au hasard.\n\nfindyourconcierge.com, est une équipe de 50 personnes en 2021, qui est à vos petits soins, avec des prestataires bien souvent exclusifs.\n\nAlors vite contactez-nous et parlez nous de votre projet :\nToute l’équipe en France : +212 670 670 456.\n\nEnfin n’hésitez pas à vous y prendre tôt à l’avance pour assurer le choix des villas et la disponibilité de nos prestataires sur place."
    },
    "an": {
        "intro" : "Come party in Marrakech!",
        "grand titre" : "20 years, 50 years, etc.\n10 years of marriage, 50 years of marriage, etc.",
        "text" : "Since 2017, findyourconcierge.com has organized dozens of birthday parties.\nSo whatever the circumstances, we will make this magical day unforgettable.\nSo let us know your dream and we will make it happen! From simple to more sophisticated parties, we have experience.\n\nHave very economical parties and plan to plan your party during the week rather than the weekend.\nIndeed, weekends are often very busy for us and for us. we are very flexible on our rates if your party takes place during the week. So tell us about your project and you will be surprised at the speed and precision with which we respond to you.\n\nEverything is possible and possible thanks to our many years of experience in organizing events in Marrakech:\ n\nFire eater\nLocal musicians - Group of Gnaouas\nDJ experienced and professional\nBOSE sound - RVS\nLight Show and enhancement of the plants and the manor\nOriental dancers\nPresence of camels \nLaunch of Thai lanterns\nBut at risk to repeat ourselves: it is above all our experience of the party that will be the success of your birthday stay, because we plan everything and we leave nothing to chance.\n\nfindyourconcierge.com, is a team of 50 people in 2021 , which is very caring for you, with very often exclusive service providers.\n\nSo quickly contact us and tell us about your project:\nThe whole team in France: +212 670 670 456.\n\nFinally n' do not hesitate to go early in advance to ensure the choice villas and the availability of our service providers on site."
    }
}